// Opcodes for the 8-bit CPU mode of Angua
// Scot W. Stevenson <scot.stevenson@gmail.com>
// First version: 07. Nov 2018
// First version: 07. Nov 2018

package cpu8

import (
	"fmt"
)

var opcodes8 = [...]func(c *Cpu8){opc00, opc01, opcE8}

// TODO Dummy functions, these will be generated by a script later
func opc00(c *Cpu8) {
	fmt.Println("DUMMY BRK")
}

func opc01(c *Cpu8) {
	fmt.Println("DUMMY ora.xi")
}

func opcE8(c *Cpu8) {
	c.X += 1
	c.PC += 1
}
